general {
    lock_cmd = system-lock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = sleep 1 && hyprctl dispatch dpms on
    inhibit_sleep = 3
}

# Dim display and keyboard backlight after 2.5 minutes.
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

listener {
    timeout = 150
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
    on-resume = brightnessctl -rd rgb:kbd_backlight
}

# Lock the session after 5 minutes.
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Turn the display off after 6 minutes.
listener {
    timeout = 360
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}

# Suspend the machine after 20 minutes.
listener {
    timeout = 1200
    on-timeout = systemctl suspend
}
