--ozone-platform-hint=auto
--enable-features=VaapiVideoDecoder
--ignore-gpu-blocklist
--process-per-site
--enable-gpu-rasterization
--enable-zero-copy
--force-dark-mode
--enable-features=WebUIDarkMode
