#!/usr/bin/env sh

if ! command -v light >/dev/null; then
    echo " !dep "
    exit 33
fi

ICONS=("󰃞 " "󰃟 " "󰃠 ")
command="light"

case $BLOCK_BUTTON in
    3) # right click: toggle min/full brightness
      rounded=$($command | cut -d '.' -f1)
      if [ "$rounded" -ge 50 ]; then
        command="light -S 100"
      else
        command="light -S 1"
      fi
      ;;
    4) # scroll up
      command="light -A 1"
      ;;
    5) # scroll down
      command="light -U 1"
      ;;
esac

current=$($command | cut -d '.' -f1)

if [ -z "$current" ]; then
    echo "${ICONS[1]}"
    exit 0
fi

icon=${ICONS[$(expr ${current} \* \( ${#ICONS[@]} - 1 \) / 100)]}
echo "${icon}${current}%"
