#!/bin/bash

if ! command -v tuned-adm >/dev/null; then
  echo " !dep "
  exit 33
fi

get_power_profile() {
    local profile=$(tuned-adm active | sed 's/.*: //g')
    case $profile in
        throughput-performance)
            profile="performance"
            ;;
        balanced-battery)
            profile="balanced"
            ;;
        powersave)
            profile="power-saver"
            ;;
    esac
    echo $profile
}

profile=$(get_power_profile)

if [ "${BLOCK_BUTTON}" != "" ]; then
    case $profile in
        performance)
            tuned-adm profile balanced-battery
            ;;
        balanced)
            tuned-adm profile throughput-performance
            ;;
        power-saver)
             tuned-adm profile balanced-battery
            ;;
        *)
            exit -1
            ;;
    esac

    profile=$(get_power_profile)
fi

echo "󱐋 ${profile}"
