#!/bin/bash
#
# Saumon i3blocks scripts
# volume (pulseaudio volume display and control)

if ! command -v pactl >/dev/null; then
  echo " !dep "
  exit 33
fi

if ! command -v pamixer >/dev/null; then
  echo " !dep "
  exit 33
fi

case $BLOCK_BUTTON in
  1) pgrep pavucontrol || i3-msg -q exec i3-msg -q exec env GDK_SCALE=2 pavucontrol ;; # click: bring up volume mixer
  3) pamixer -t ;;   # right click: toggle mute
  4) pamixer -i 5 ;; # scroll up: increase vol by 4%
  5) pamixer -d 5 ;; # scroll down: decrease vol by 4%
esac

active_sink=$(pactl get-default-sink)
sink=$(pactl list sinks | grep -A100 "Name: $active_sink")
if [[ "$sink" == *"bluez"* ]]; then isbluetooth=1; fi
if [[ "$sink" == *"Active Port: analog-output-headphone"* ]]; then isheadphone=1; fi
# I can we can use `pactl get-sink-mute @DEFAULT_SINK@` but it's less efficient :)
if [[ "$sink" == *"Mute: yes"* ]]; then ismuted=1; fi
volume=$(echo "$sink" | grep "Volume: " | head -1 | awk '{print $5}' | tr -d '%')

if [ -n "$isbluetooth" ]; then
  if [ -n "$ismuted" ]; then
    color="#997CC5"
  else
    color="#4a74ff"
  fi
elif [ -n "$isheadphone" ]; then
  if [ -n "$ismuted" ]; then
    color="#997CC5"
  else
    color="#F8E744"
  fi
elif [ -n "$ismuted" ]; then
  color="#997CC5"
else
  color="#dddddd"
fi

printf "<span color='%s'>" "$color"

if [ -n "$ismuted" ]; then
  printf "<s>"
fi
if [ -n "$isbluetooth" ]; then
  printf " "
fi
if [ "$volume" -ge 40 ]; then
  printf " %s" "$volume"
else
  printf " %s" "$volume"
fi

printf "%%"

if [ -n "$ismuted" ]; then
  printf "</s>"
fi

echo "</span>"
